#!/bin/sh -e

patch -p1 < 001-disable-intltool.patch
patch -p1 < 001-fix-musl-build.patch

# autoconf warnings are treated as errors.
set +e
automake
autoconf
set -e

./configure \
    --prefix=/usr \
    --disable-nls \
    --with-media-dir=/mnt/

make

# 'make install' requires root privileges.
install -Dm4755 src/pmount "$1/usr/bin/pmount"
install -Dm4755 src/pumount "$1/usr/bin/pumount"
install -Dm0644 man/pmount.1 "$1/usr/share/man/man1/pmount.1"
install -Dm0644 man/pumount.1 "$1/usr/share/man/man1/pumount.1"
