#!/bin/sh -e

export DESTDIR="$1"

cmake -B build \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DCMAKE_INSTALL_LIBDIR=lib \
    -DCMAKE_BUILD_TYPE=Release \
    -DLIBXML2_WITH_THREADS=ON \
    -DLIBXML2_WITH_PYTHON=OFF \
    -DLIBXML2_WITH_ICU=OFF \
    -DLIBXML2_WITH_DOCB=OFF

cmake --build   build
cmake --install build
